# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boss.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BossWindow(object):
    def setupUi(self, BossWindow):
        BossWindow.setObjectName("BossWindow")
        BossWindow.resize(800, 572)
        self.centralwidget = QtWidgets.QWidget(BossWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 511, 391))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 90, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 120, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 150, 61, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(570, 180, 61, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(570, 210, 61, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(570, 240, 61, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(670, 90, 61, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(670, 120, 61, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(670, 150, 61, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(670, 180, 61, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(670, 210, 61, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(670, 240, 61, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(530, 490, 131, 20))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.ignoreButton = QtWidgets.QPushButton(self.centralwidget)
        self.ignoreButton.setGeometry(QtCore.QRect(530, 420, 75, 23))
        self.ignoreButton.setObjectName("ignoreButton")
        self.suspendButton = QtWidgets.QPushButton(self.centralwidget)
        self.suspendButton.setGeometry(QtCore.QRect(680, 490, 75, 23))
        self.suspendButton.setObjectName("suspendButton")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(60, 400, 371, 121))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(28)
        self.label_13.setFont(font)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(530, 460, 121, 21))
        self.label_14.setObjectName("label_14")
        BossWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BossWindow)
        self.statusbar.setObjectName("statusbar")
        BossWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(BossWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        BossWindow.setMenuBar(self.menuBar)
        self.action1 = QtWidgets.QAction(BossWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(BossWindow)
        self.action2.setObjectName("action2")
        self.menu.addAction(self.action1)
        self.menu.addAction(self.action2)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(BossWindow)
        QtCore.QMetaObject.connectSlotsByName(BossWindow)

    def retranslateUi(self, BossWindow):
        _translate = QtCore.QCoreApplication.translate
        BossWindow.setWindowTitle(_translate("BossWindow", "MainWindow"))
        self.label.setText(_translate("BossWindow", "温度"))
        self.label_2.setText(_translate("BossWindow", "相对湿度"))
        self.label_3.setText(_translate("BossWindow", "体感温度"))
        self.label_4.setText(_translate("BossWindow", "风向角"))
        self.label_5.setText(_translate("BossWindow", "风力等级"))
        self.label_6.setText(_translate("BossWindow", "风速"))
        self.label_7.setText(_translate("BossWindow", "TextLabel"))
        self.label_8.setText(_translate("BossWindow", "TextLabel"))
        self.label_9.setText(_translate("BossWindow", "TextLabel"))
        self.label_10.setText(_translate("BossWindow", "TextLabel"))
        self.label_11.setText(_translate("BossWindow", "TextLabel"))
        self.label_12.setText(_translate("BossWindow", "TextLabel"))
        self.ignoreButton.setText(_translate("BossWindow", "忽略"))
        self.suspendButton.setText(_translate("BossWindow", "发送"))
        self.label_14.setText(_translate("BossWindow", "请输入停工时长(天):"))
        self.menu.setTitle(_translate("BossWindow", "测试"))
        self.action1.setText(_translate("BossWindow", "模拟警报"))
        self.action2.setText(_translate("BossWindow", "打开图片"))

